name: Deploy Ombu

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 📦 Checkout del código
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Validación manual de secrets (sin bucle dinámico)
      - name: Validar secrets del repositorio
        run: |
          missing=0
          if [ -z "${{ secrets.DOCKER_HUB_USER }}" ]; then echo "❌ Falta DOCKER_HUB_USER"; missing=1; fi
          if [ -z "${{ secrets.DOCKER_HUB_TOKEN }}" ]; then echo "❌ Falta DOCKER_HUB_TOKEN"; missing=1; fi
          if [ -z "${{ secrets.DO_HOST }}" ]; then echo "❌ Falta DO_HOST"; missing=1; fi
          if [ -z "${{ secrets.DO_USER }}" ]; then echo "❌ Falta DO_USER"; missing=1; fi
          if [ -z "${{ secrets.DO_SSH_KEY }}" ]; then echo "❌ Falta DO_SSH_KEY"; missing=1; fi
          if [ -z "${{ secrets.GH_PAT }}" ]; then echo "❌ Falta GH_PAT"; missing=1; fi
          if [ -z "${{ secrets.DOTENV }}" ]; then echo "❌ Falta DOTENV"; missing=1; fi
          if [ -z "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" ]; then echo "❌ Falta GOOGLE_CREDENTIALS_JSON"; missing=1; fi

          if [ $missing -ne 0 ]; then
            echo "❌ Faltan variables obligatorias, abortando workflow."
            exit 1
          fi
          echo "✅ Todos los secrets requeridos están definidos correctamente."

      # 🔑 Login en Docker Hub
      - name: Log in en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 🐳 Build & Push de la imagen a Docker Hub
      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER }}/ombu:latest

      # 🚀 Deploy remoto en DigitalOcean
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            set -e
            echo "📦 Iniciando despliegue remoto en /srv/ombu..."

            # Crear estructura si no existe
            mkdir -p /srv/ombu/credentials
            cd /srv/ombu

            # Clonar o actualizar el repo
            if [ ! -d "/srv/ombu/.git" ]; then
              echo "📥 Clonando repo..."
              rm -rf /srv/ombu
              git clone https://oauth2:${{ secrets.GH_PAT }}@github.com/dtech-dh/ombu.git /srv/ombu
            else
              echo "🔄 Actualizando repo existente..."
              cd /srv/ombu
              git reset --hard
              git pull https://oauth2:${{ secrets.GH_PAT }}@github.com/dtech-dh/ombu.git main
            fi

            # Crear .env
            echo "📝 Generando .env"
            echo "${{ secrets.DOTENV }}" > /srv/ombu/.env

            # Crear credenciales Google
            echo "🔑 Generando service_account.json"
            echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > /srv/ombu/credentials/service_account.json

            # Validar que exista y tenga contenido
            if [ ! -s /srv/ombu/credentials/service_account.json ]; then
              echo "❌ Error: el archivo service_account.json está vacío o no existe"
              exit 1
            fi

            echo "🐳 Deploy con Docker Compose..."
            docker compose pull
            docker compose up -d --build

            echo "✅ Despliegue completado correctamente."
