name: Deploy Ombu

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 📦 Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Validación de secrets antes de continuar
      - name: Validar secrets del repositorio
        run: |
          missing=0
          for secret in DOCKER_HUB_USER DOCKER_HUB_TOKEN DO_HOST DO_USER DO_SSH_KEY GH_PAT DOTENV GOOGLE_CREDENTIALS_JSON; do
            if [ -z "${{ secrets[$secret] }}" ]; then
              echo "❌ Falta $secret"
              missing=1
            fi
          done
          if [ $missing -ne 0 ]; then
            echo "❌ Faltan variables obligatorias, abortando workflow."
            exit 1
          fi
          echo "✅ Todos los secrets requeridos están definidos"

      # 🔑 Login a Docker Hub
      - name: Log in en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 🐳 Build & Push de la imagen
      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER }}/ombu:latest

      # 🚀 Deploy remoto en Droplet DigitalOcean
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            set -e
            echo "📦 Iniciando despliegue remoto en /srv/ombu..."

            # Crear estructura si no existe
            mkdir -p /srv/ombu/credentials
            cd /srv/ombu

            # Clonar o actualizar el repo
            if [ ! -d "/srv/ombu/.git" ]; then
              echo "📥 Primera implementación: clonando repo..."
              rm -rf /srv/ombu
              git clone https://oauth2:${{ secrets.GH_PAT }}@github.com/dtech-dh/ombu.git /srv/ombu
            else
              echo "🔄 Actualizando repo existente..."
              cd /srv/ombu
              git reset --hard
              git pull https://oauth2:${{ secrets.GH_PAT }}@github.com/dtech-dh/ombu.git main
            fi

            # Escribir el archivo .env
            echo "📝 Generando archivo .env"
            echo "${{ secrets.DOTENV }}" > /srv/ombu/.env

            # Escribir credenciales de Google (Service Account)
            echo "🔑 Generando service_account.json"
            echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > /srv/ombu/credentials/service_account.json

            # Verificar que el archivo sea válido
            if [ ! -s /srv/ombu/credentials/service_account.json ]; then
              echo "❌ Error: el archivo service_account.json está vacío o no existe"
              exit 1
            fi

            echo "🐳 Ejecutando docker compose..."
            docker compose pull
            docker compose up -d --build

            echo "✅ Despliegue completado correctamente."
